language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - travis_retry composer self-update
  - travis_retry composer install

script:
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then vendor/bin/phpunit; fi;'
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then vendor/bin/phpunit --coverage-clover=coverage.clover; fi;'

after_script:
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi;'
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi;'


notifications:
  slack:
    secure: MG9xDn2cKFMa0HG0+7Q71ruifBbHfbXJ4KA/jqgjFL5Fn2R1GDfVi/LzXe7haDiZmgoDY7pZHim7bIaG4RwInBkZ2WXqvaD8HeRxLtmZmzPOtcwlGrCte7IemcJP3uwToIIm79Im6of06A+tWdHODqe/BTGCxnSiQlOKHNccGf4=
